### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by tarwich** [tschoffelen/gha#2]
Thanks for this project! It is always nice to be able to test out actions without having to push. I'm getting an error when trying to run, however. 

<details><summary>System Information</summary>
<p>

```yaml
Operating System:
  Windows: 10.0.17763
  arch: x64

Applications:
  node: v11.10.0
  gha: 1.0.0
  npm: 6.7.0
```

</p>
</details>

### What happened was...

```
>gha
Running New workflow...

===> GitHub Action for npm
curl: (23) Failed writing body (0 != 2740)
The syntax of the command is incorrect.
tar: Error opening archive: Failed to open '/tmp/gha.actions-npm-59b64a598378f31e49cb76f27d6f3312b582f680.tgz'
'rm' is not recognized as an internal or external command,
operable program or batch file.

Could not find Dockerfile: /tmp/gha.actions-npm-59b64a598378f31e49cb76f27d6f3312b582f680/*//Dockerfile
```
