### ISSUE TITLE
Having trouble targeting a workflow file

### ISSUE THREAD

**Issue by retzion** [tschoffelen/gha#5]
```
MacBook-Pro new_repo % ls .github/workflows
main.yml
MacBook-Pro new_repo % gha -f .github/workflows/main.yml
fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, open '.github/main.workflow'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/Users/user1/.nvm/versions/node/v11.0.0/lib/node_modules/gha/index.js:24:30)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
```

**Comment by retzion** [comment]
I moved my workflow to the path the module is looking for (`.github/main.workflow`) and now get this error.

```
MacBook-Pro new_repo % gha  

/Users/user1/.nvm/versions/node/v11.0.0/lib/node_modules/gha/node_modules/hcl/lib/hcl.js:2303
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
      ^
SyntaxError: Expected "=", "{", [a-zA-Z0-9_$\-], [a-zA-Z_] or string but ":" found.
```

This is my workflow:
```
name: BugCatcher

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: npm install
      - name: build
        run: npm build
      - name: BugCatcher GitHub Action
        uses: faster-than-light/github-action@0.1.14
        with:
          FTL_SID: ${{ secrets.FTL_SID }}
          SEVERITY_THRESHOLD: medium
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks for any help you can offer. I don't know if these are bugs or if I'm just buggy ;-)
